// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 1500m,
                            ProductName = "IPhone 11 Pro Max"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 1700m,
                            ProductName = "IPhone 12 Pro Max"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            Price = 2000m,
                            ProductName = "IPhone 13 Pro Max"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 2500m,
                            ProductName = "IPhone 14 Pro Max"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            Price = 3500m,
                            ProductName = "IPhone 15 Pro Max"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
